### PR TITLE
Add Docker instructions

### PR DESCRIPTION
**Pull request by nurupo**
It seemed somewhat non-trivial to create a separate Travis-CI matrix for testing the Docker image, it would likely require making separate scripts for what Travis currently does and another for testing Docker container, and I'm not sure how you want this to be done, so I didn't do it.

---
This change is [Reviewable](https://reviewable.io/reviews/toktok/apidsl/22)

### CODE REVIEW

**Comment by robinlinden** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 37 at r1](https://reviewable.io:443/reviews/toktok/apidsl/22#-K_e6kzR_fzyCF1R6dCz:-K_e6kzSv4Xokad-6Igq:bbxg1gq) ([raw file](https://github.com/toktok/apidsl/blob/f0164cb93d5e59f0bf7fd0a62409848eb820b5c9/README.md#L37)):*
> ```Markdown
> #### Usage
> 
> [Get Docker on your system](https://docs.docker.com/engine/installation/linux/debian/).
> ```

Maybe https://docs.docker.com/engine/installation/linux/ is a more suitable link?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/apidsl/22)*

**Comment by nurupo** [comment]
*[README.md, line 37 at r1](https://reviewable.io:443/reviews/toktok/apidsl/22#-K_e6kzR_fzyCF1R6dCz:-K_e7FZsDtsD1rEBCOrc:b-vswrkg) ([raw file](https://github.com/toktok/apidsl/blob/f0164cb93d5e59f0bf7fd0a62409848eb820b5c9/README.md#L37)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Maybe https://docs.docker.com/engine/installation/linux/ is a more suitable link?
</blockquote></details>

Good catch, you are right.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/apidsl/22)*

**Comment by nurupo** [comment]
*[README.md, line 37 at r1](https://reviewable.io:443/reviews/toktok/apidsl/22#-K_e6kzR_fzyCF1R6dCz:-K_e7RVysVaMYVypDSPF:bt2vr1b) ([raw file](https://github.com/toktok/apidsl/blob/f0164cb93d5e59f0bf7fd0a62409848eb820b5c9/README.md#L37)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Good catch, you are right.
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/apidsl/22)*

**Comment by robinlinden** [comment]
:lgtm_strong:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Dockerfile, line 6 at r1](https://reviewable.io:443/reviews/toktok/apidsl/22#-K_e8mVEGbPxitmekelS:-K_e8mVFXO2zZvKOEuYi:bqu2rlb) ([raw file](https://github.com/toktok/apidsl/blob/f0164cb93d5e59f0bf7fd0a62409848eb820b5c9/Dockerfile#L6)):*
> ```Dockerfile
>     apt-get install --no-install-recommends -y \
>       git \
>       ca-certificates \
> ```

Can you sort these alphanumerically?

---

*[Dockerfile, line 10 at r1](https://reviewable.io:443/reviews/toktok/apidsl/22#-K_e9tz5gef7tdtNXPC2:-K_e9tz6C-4BhlLQysfA:b-w94n9m) ([raw file](https://github.com/toktok/apidsl/blob/f0164cb93d5e59f0bf7fd0a62409848eb820b5c9/Dockerfile#L10)):*
> ```Dockerfile
>       make \
>       opam && \
>     apt-get clean && \
> ```

This line isn't required as `apt-get clean` is run automatically on Debian and Ubuntu images.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/apidsl/22#-:-K_eDU0Qy2fvEoTmtp6x:b-jbsf8z)*

**Comment by nurupo** [comment]
*[Dockerfile, line 6 at r1](https://reviewable.io:443/reviews/toktok/apidsl/22#-K_e8mVEGbPxitmekelS:-K_eHkDP_xtZmCizswGU:bb6un1j) ([raw file](https://github.com/toktok/apidsl/blob/f0164cb93d5e59f0bf7fd0a62409848eb820b5c9/Dockerfile#L6)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

Can you sort these alphanumerically?
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/apidsl/22)*

**Comment by nurupo** [comment]
*[Dockerfile, line 10 at r1](https://reviewable.io:443/reviews/toktok/apidsl/22#-K_e9tz5gef7tdtNXPC2:-K_eGCQbRhwkeVPf2aYZ:bw3he88) ([raw file](https://github.com/toktok/apidsl/blob/f0164cb93d5e59f0bf7fd0a62409848eb820b5c9/Dockerfile#L10)):*
<details><summary><i>Previously, robinlinden (Robin Lindén) wrote…</i></summary><blockquote>

This line isn't required as `apt-get clean` is run automatically on Debian and Ubuntu images.
</blockquote></details>

I see https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/.

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/apidsl/22)*

**Comment by robinlinden** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/toktok/apidsl/22)*

**Pull request merged**
